---
- name: Ensure NVIDIA repository key is present
  ansible.builtin.apt_key:
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/3bf863cc.pub
    state: present

- name: Add NVIDIA repository
  ansible.builtin.apt_repository:
    repo: "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/ /"
    state: present

- name: Install NVIDIA drivers
  ansible.builtin.apt:
    name: "{{ nvidia_driver_package | default('nvidia-driver-550-open') }}"
    state: present
    update_cache: yes

- name: Enable persistence mode
  ansible.builtin.shell: |
    nvidia-smi -pm 1
  when: ansible_facts.gpus is defined
  args:
    warn: false
