name: Sync NVIDIA Docs

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests pyyaml beautifulsoup4

      - name: Sync docs
        run: make vendor-sync

      - name: Commit & PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: sync NVIDIA docs"
          title: "Sync NVIDIA docs"
          branch: sync-nvidia-docs
